### ISSUE TITLE
Sensor

### ISSUE THREAD

**Issue by GuaiYiHu** [xiaomi-classic-dev/android_device_xiaomi_virgo-old#23]
Go from st_mve to leo.

**Comment by DrRamm** [comment]
multihal

**Comment by GuaiYiHu** [comment]
in fact, fixed in branch lineage-15.1-m with xiaomi's new kernel source. :p

**Comment by DrRamm** [comment]
Multihal is better

**Comment by GuaiYiHu** [comment]
So this issue is for the changes to make sensor works on the new kernel source xiaomi released on christmas. Not just fix the sensor.
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/cancro-m-oss
See the commits before.
https://github.com/xiaomi-note-dev/android_device_xiaomi_virgo/commits/lineage-15.1-m/sensors

**Comment by DrRamm** [comment]
What about camera?

**Comment by GuaiYiHu** [comment]
Camera works so good on my xiaomi note.
I didn't test mi3/mi4.
I updated camera blobs from MIUI dev.
https://github.com/xiaomi-note-dev/android_vendor_xiaomi_virgo/commit/e118627d96dbe739961e0157e5597a007fa82594

**Comment by DrRamm** [comment]
Thanks u

**Comment by GuaiYiHu** [comment]
I will try to bring up O for mi3/mi4 this winter holiday.

**Comment by DrRamm** [comment]
I almost done it based on ur commits. Hope that fix most of issues today

**Comment by GuaiYiHu** [comment]
Not all the commits are useful to cancro, some commits are for the features of virgo.

**Comment by DrRamm** [comment]
such as?

**Comment by DrRamm** [comment]
btw can u remind me diff between virgo and cancro
